import type { Event } from '@/lib/types';

export const events: Event[] = [
  { id: '1', name: 'Global Tech Summit 2024', date: '2024-10-15', location: 'Bangalore, KA', description: 'A massive conference for tech enthusiasts and professionals, focusing on the future of artificial intelligence, cloud computing, and sustainable tech.', tags: ['Tech', 'Networking', 'AI'], imageUrl: 'https://placehold.co/600x400/7c3aed/ffffff.png' },
  { id: '2', name: 'Mumbai Startup Pitch Night', date: '2024-09-22', location: 'Mumbai, MH', description: 'An exciting evening where innovative startups pitch their game-changing ideas to a panel of venture capitalists and angel investors. A great networking opportunity.', tags: ['Business', 'Startups', 'Investing'], imageUrl: 'https://placehold.co/600x400/1e40af/ffffff.png' },
  { id: '3', name: 'Pune Design Workshop', date: '2024-11-05', location: 'Pune, MH', description: 'A hands-on workshop for experienced designers to learn the latest trends in UX/UI, generative design, and virtual reality interfaces.', tags: ['Design', 'Workshop', 'UX/UI'], imageUrl: 'https://placehold.co/600x400/db2777/ffffff.png' },
  { id: '4', name: 'Goa Indie Music Festival', date: '2024-12-01', location: 'Goa', description: 'A vibrant, three-day festival celebrating independent music artists from across the country, set against a scenic beach backdrop with food stalls and art installations.', tags: ['Music', 'Entertainment', 'Festival'], imageUrl: 'https://placehold.co/600x400/ea580c/ffffff.png' },
  { id: '5', name: 'Delhi Literary Festival', date: '2024-10-28', location: 'Delhi', description: 'A celebration of literature and ideas, featuring panel discussions, poetry slams, and book readings with renowned authors from India and around the world.', tags: ['Books', 'Arts', 'Culture'], imageUrl: 'https://placehold.co/600x400/78350f/ffffff.png' },
  { id: '6', name: 'Hyderabad Hackathon 2024', date: '2024-11-15', location: 'Hyderabad, TS', description: 'A 24-hour hackathon where developers, designers, and innovators build projects to solve real-world social problems. Prizes and recruitment opportunities available.', tags: ['Tech', 'Competition', 'Social Good'], imageUrl: 'https://placehold.co/600x400/047857/ffffff.png' },
  { id: '7', name: 'Gurgaon Digital Marketing Conclave', date: '2024-09-30', location: 'Gurgaon, HR', description: 'A conclave for marketing professionals to explore the future of digital marketing, including SEO, content marketing, AI in advertising, and influencer strategies.', tags: ['Marketing', 'Digital', 'Business'], imageUrl: 'https://placehold.co/600x400/ca8a04/ffffff.png' },
  { id: '8', name: 'Chandigarh Organic Farmers Market', date: '2024-10-05', location: 'Chandigarh', description: 'A weekend market featuring fresh, organic produce directly from local farmers. Includes workshops on sustainable agriculture and healthy living.', tags: ['Food', 'Health', 'Community'], imageUrl: 'https://placehold.co/600x400/16a34a/ffffff.png' },
  { id: '9', name: 'Kolkata International Film Festival', date: '2024-11-10', location: 'Kolkata, WB', description: 'Experience a week of cinematic brilliance with screenings of international films, masterclasses by renowned directors, and panel discussions.', tags: ['Film', 'Entertainment', 'Culture'], imageUrl: 'https://placehold.co/600x400/4f46e5/ffffff.png' },
  { id: '10', name: 'Chennai Fintech Summit', date: '2024-10-20', location: 'Chennai, TN', description: 'A summit dedicated to the future of financial technology, exploring blockchain, digital payments, and the role of AI in finance.', tags: ['Finance', 'Tech', 'Fintech'], imageUrl: 'https://placehold.co/600x400/be123c/ffffff.png' },
  { id: '11', name: 'Jaipur Heritage Art Expo', date: '2024-11-25', location: 'Jaipur, RJ', description: 'An exposition of traditional Rajasthani art, from miniature paintings to blue pottery. Meet the artisans and see live demonstrations.', tags: ['Art', 'Culture', 'Heritage'], imageUrl: 'https://placehold.co/600x400/fbbf24/000000.png' },
  { id: '12', name: 'Ahmedabad Food Carnival', date: '2024-12-08', location: 'Ahmedabad, GJ', description: 'A gastronomic journey through the best of Gujarati cuisine and street food from across India. Live music and cooking competitions.', tags: ['Food', 'Festival', 'Entertainment'], imageUrl: 'https://placehold.co/600x400/f97316/ffffff.png' },
];
